package-lock.json
package.json
packages/k8s/README.md
packages/k8s/src/hooks/constants.ts
packages/k8s/tests/test-setup.ts
releaseNotes.md

This pr loosens the restriction on the runner claim name, letting it fallback to the pod name -work rather then failing if it is not set. This is helpful in cases where pod names are generated automatically, and the [downward api ](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/)doesn't give appropriate flexibility to set this env.

Make K8s claim name optional

---

packages/k8s/src/hooks/prepare-job.ts
packages/k8s/src/hooks/run-script-step.ts
packages/k8s/src/index.ts
packages/k8s/src/k8s/index.ts
packages/k8s/tests/test-setup.ts

`JSON.stringify` hides errors, so lets remove those invocations and replace them with just printing the error

Don't use JSON.stringify for errors

---

packages/docker/src/dockerCommands/container.ts
packages/docker/src/utils.ts
packages/docker/tests/utils-test.ts

exposing env variables from runner with `DOCKER_` prefix to respect docker options set on host

---

packages/k8s/src/hooks/prepare-job.ts

Closes #44
This change does not overwrite entrypoint if when createPodSpec is not executed for a jobContainer.
This is created as a draft to revisit if we can incorporate `--entrypoint` overwrite

k8s: don't overwriting service entrypoint

---

packages/docker/src/index.ts
packages/k8s/src/index.ts

There might be situation where reading from standard input fails. In that case, we should encapsulate that exception within the try catch block to avoid unhandeled Promise rejection exception and provide more information about the error

docker and k8s: read from stdin inside try catch block

---

packages/k8s/src/index.ts

Fixes #41 
Also, have consistency with docker hook for the way the exit is called

Exit from run k8s not allowing promise rejection

---

packages/k8s/src/k8s/utils.ts
packages/k8s/tests/k8s-utils-test.ts
packages/k8s/tests/run-script-step-test.ts

Previously, environment variables like:
```
env:
LD_PRELOAD: /__w/_tool/CodeQL/2.12.6-20230403/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so    
```
would wrongly get expanded by the shell when running a job via the k8s scripts. This may lead to errors like:
```
ERROR: ld.so: object '/__w/_tool/CodeQL/2.12.6-20230403/x64/codeql/tools/linux64/__trace.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
See a complete log for context: https://github.com/matihost/monorepo/actions/runs/4638170156/jobs/8207744339
This pull request:
* throws an error when a `$` is used in the name of an environment variable
* escapes any `$` symbols in the value of an environment variable
This behaviour is the same as other special shell characters such as `'` and `"`.

k8s: handle $ symbols in environment variable names and values

---

packages/docker/src/dockerCommands/container.ts

The optional --config option must come *before* the pull argument.
```
❯ docker pull --config file debian:latest
unknown flag: --config
See 'docker pull --help'.
❯ docker --config file pull debian:latest
latest: Pulling from library/debian
bba7bb10d5ba: Already exists
Digest: sha256:d568e251e460295a8743e9d5ef7de673c5a8f9027db11f4e666e96fb5bed708e
Status: Downloaded newer image for debian:latest
docker.io/library/debian:latest
❯ docker info
Client: Docker Engine - Community
Version:    24.0.2
Context:    default
Debug Mode: false
Plugins:
buildx: Docker Buildx (Docker Inc.)
Version:  v0.10.5
Path:     /usr/libexec/docker/cli-plugins/docker-buildx
compose: Docker Compose (Docker Inc.) …
```

Fix argument order for 'docker pull'

---

packages/docker/src/hooks/prepare-job.ts

related: https://github.com/actions/runner-container-hooks/issues/44
When using service container with container hooks for docker, is it possible to stop the overwriting of the entrypoint?
Currently, container hooks for docker does not allow the use of service container for some docker images.
This is because the setupContainer function sets `tail` as entryPoint field in any case.
This behavior prevents, for example, postgres or mysql cannot be started (by overriding their configured entrypoint).
setupContainer function: 
https://github.com/actions/runner-container-hooks/blob/ebbe2bdaffea3efb4f0ac1eaf1b381be53a78bdc/packages/docker/src/hooks/prepare-job.ts#L178-L179
I think this is the same problem as https://github.com/actions/runner-container-hooks/issues/44. So, I tried to write a …

docker: Do not overwrite entrypoint if it has already been set or if it is Service container

---

packages/k8s/src/hooks/run-container-step.ts
packages/k8s/tests/run-container-step-test.ts

Relax limitation on entrypoint allowing container actions to be executed without the entrypoint specified

---

packages/k8s/src/hooks/prepare-job.ts
packages/k8s/src/k8s/index.ts
packages/k8s/src/k8s/utils.ts
packages/k8s/tests/prepare-job-test.ts

As described in https://github.com/actions/runner-container-hooks/issues/112 workflow pods aren't going via the kubernetes scheduler, resulting in failed "initialize containers" steps if the already selected node is out of resources. With the following changes I was able to get this working.
This PR adds two new environment variables: `ACTIONS_RUNNER_USE_KUBE_SCHEDULER` and `ACTIONS_RUNNER_PREPARE_JOB_TIMEOUT_SECONDS`.
When set to `true`, the former skips setting the node name and let's the kubernetes scheduler handle the workflow pod. This would only work on a single node cluster (important for the newly added test) or when `ReadWriteMany` volumes are used.
The latter can be used to increase the timeout to for example 6 hours from the default 10 minutes. This will be necessary for …

Add option to use the kubernetes scheduler for workflow pods

---

packages/docker/package-lock.json
packages/docker/package.json
packages/docker/src/dockerCommands/container.ts
packages/docker/src/utils.ts
packages/docker/tests/run-script-step-test.ts
packages/docker/tests/utils-test.ts
packages/k8s/package-lock.json
packages/k8s/package.json
packages/k8s/src/hooks/prepare-job.ts
packages/k8s/src/hooks/run-container-step.ts
packages/k8s/src/k8s/index.ts
packages/k8s/src/k8s/utils.ts
packages/k8s/tests/run-container-step-test.ts

When runner passes arguments to the hook, there may be situations where quoted strings are interpreted as separate arguments.
This PR addresses the issue and fixes the arguments based on `shlex` expansion
Fixes the [issue in this discussion](https://github.com/orgs/community/discussions/70488)

Docker and K8s: Fix shell arguments when split by the runner

---

packages/k8s/src/k8s/index.ts

Exec returns a websocket. If websocket fails, we should reject the promise. Otherwise, websocket will call a callback. Since at that point, websocket is not failing, we can safely resolve or reject the promise.
Fixes #107

Switch exec pod promise to reject on websocket error

---

packages/k8s/src/hooks/run-container-step.ts

Currently, when child pod (e.g. container action related) fails at startup (e.g. wrong input parameters for entrypoint), its logs are not read by runner and not pushed to GH UI. 
Such PR changes this behavior.

Read logs also from failed child (container job/container action) pod

---

examples/extension.yaml
packages/k8s/src/hooks/constants.ts
packages/k8s/src/hooks/prepare-job.ts
packages/k8s/src/k8s/utils.ts
packages/k8s/tests/prepare-job-test.ts

Related to discussion under: https://github.com/actions/runner-container-hooks/issues/132
@nikola-jokic not sure how to upgrade ADR (what is your process) - awaiting your recommendation

Use ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE to extend service containers

---

packages/k8s/src/k8s/utils.ts
packages/k8s/tests/k8s-utils-test.ts

`/github/workflow` is set via env GITHUB_EVENT_PATH also in docker actions.
Such path is mount in container jobs pods, and should be(?) mount in similar fashion in other child pods (in this case docker action pods), especially that some docker actions from marketplace, use this path.
Having it inconsistent for container job pod and for docker action pod, makes it impossible to use with ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE and mount via extension, which is shared for both - it will work for docker action pods, but will fail for container job pod (duplicate mount point).
Adding it as default mount seems the only option to be able to properly utilize this ENV (and events in general).

Mount /github/workflow to docker action pods

---

packages/k8s/package-lock.json
packages/k8s/package.json

To support the latest Kubernetes features in the k8s package, we need [kubernetes/client-node](https://github.com/kubernetes-client/javascript) [0.22.0](https://github.com/kubernetes-client/javascript/releases/tag/0.22.0) that supports Kubernetes 1.30.
Fixes #183.

Bump kubernetes/client-node from 0.18.1 to 0.22.0

---

package-lock.json
package.json
releaseNotes.md

Releasing the changes from #182 to support #183.
I also ran `npm audit fix` to resolve some warnings for the main `package.json` dev dependencies.

Prepare 0.6.2 Release

---

CODEOWNERS

`@actions/runner-akvelon` is not currently being used.

Remove `@actions/runner-akvelon` from CODEOWNERS

---

.github/workflows/build.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yaml

A lot of these workflows are using deprecated actions with old Node versions.
As a follow-up, we should set up Dependabot to automate this.
`.github/workflows/release.yaml` also needs to be re-written to avoid usage of `actions/create-release` and `actions/upload-release-asset` which are archived.

Update to the latest available actions

---

packages/k8s/src/k8s/index.ts

I noticed that for jobs that quickly generate a lot of logs (like super-linter) the first lines of the log are missing. However sometimes in there are the information you need to debug a problem further.
Luckily this problem is easily fixed by removing the `tailLines: 50`.

k8s: start logging from the beginning

---

packages/k8s/src/hooks/run-container-step.ts
packages/k8s/src/k8s/utils.ts

Hi maintainers, this PR is meant to accomplish two things:
1. Make the `/github/home` directory available from container actions, which is a path frequently relied on by actions creating files in a user's home (`$HOME/.netrc` for instance)
2. Surface error messages when the container hooks fail to create their required Kubernetes secret for storing environment variables.
I ran into both issues during a k8s runner deployment and a similar concern was raised in #181. I'd prefer not to maintain my internal for and custom runner image just for this additional mount if I don't have to
Thanks for the consideration!

feat(k8s): add /github/home to containerAction mounts and surface createSecretForEnvs errors #181

---

.github/workflows/build.yaml

This pull request restructures the GitHub Actions workflow for CI to improve clarity and enforce code quality checks before running tests. The main change is splitting the previous single `build` job into multiple, more focused jobs for formatting, linting, and testing Docker and Kubernetes hooks.
**Workflow Restructuring and Quality Checks:**
* Split the previous `build` job into three separate jobs: `format-and-lint`, `docker-tests`, and `k8s-tests`, to better organize the workflow and enforce sequential checks.
* Added a dedicated `format-and-lint` job that installs dependencies, bootstraps packages, builds all packages, checks code formatting, and runs the linter, ensuring no code is formatted or linted incorrectly before proceeding.
* Updated the Docker and Kubernetes test jobs …

Separate CI docker and k8s tests

---

package-lock.json
package.json
packages/docker/package-lock.json
packages/hooklib/package-lock.json
packages/k8s/package-lock.json
releaseNotes.md

This pull request updates the package to version 0.8.0 and includes several enhancements and fixes for both the Kubernetes and Docker hook implementations, as well as general dependency updates. The release notes have been updated to reflect the new features, bug fixes, and miscellaneous improvements.
Feature updates:
* Kubernetes hook: Removed dependency on the runner's volume, improving flexibility and reducing coupling.
Bug fixes:
* Docker hook: Fixed handling of read-only volumes in `createContainer`, ensuring proper volume permissions.
Miscellaneous improvements:
* Updated all dependencies and GitHub actions to their latest versions for better security and compatibility.
* Bumped package version from `0.7.0` to `0.8.0` in `package.json` to reflect the new release.

Prepare 0.8.0 release and bump dependencies once more
